---
dependencies: []

galaxy_info:
  author: geerlinguy
  description: apache 2.x for linux
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platfroms:
    - name: EL 
      versions:
        - all
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - web
    - apache
    - webserver
    - html
allow_duplicates: yes