---
- name: Create nginx directory if it does not exist
  file:
    path: /app/nginx/conf
    state: directory
    mode: 0755
    owner: devops
    group: devops
- name: Add nginx vhosts configuration
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_path }}/{{ nginx_conf_filename }}"
    owner: devops
    group: devops
    mode: 0644